### ISSUE TITLE
FEATURE: Add optional update modes

### ISSUE THREAD

**Issue by farkwun** [jason-drossis/mythicspoilerbot#21]
Some users enjoyed the old update model, in which the spoilers would get sent to users ASAP.

The current model is a poll model, where users are notified that there are existing spoilers and must take action to receive them.

While I think the current model should be the default (so as not to surprise any data-restricted users), the old functionality should be maintained for those that want it.

We could simply create a new user column `update_mode` and have it be a foreign key of some static table (perhaps called `update_modes` that only has the two current entries). It would get extracted out to the User object and exposed to the update thread when deciding how to update users.

Alternatively, we could create an options JSON blob - this will give us more flexibility when it comes to creating new options but probably be a little less controlled in terms of possible inputs.

Thoughts @robin-pham?

**Comment by robin-pham** [comment]
whats easier for you to implement in this codebase?

**Comment by farkwun** [comment]
It's much easier to just put a column in the users table, but its not at all extensible to new modes. I think the only issue with using the JSON1 SQLite extension is having to learn it
